[variables]
NODE_VERSION = "20"

[phases.build]
cmds = [
  "npm run build",
  "cp -r .next/static .next/standalone/.next/static",
  "cp -r public .next/standalone/public"
]

[start]
cmd = "node .next/standalone/server.js"
